# Generated by Django 5.0.14 on 2025-05-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCama',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IdEstadoCama')),
                ('descripcion', models.CharField(max_length=255, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'EstadoCama',
                'verbose_name_plural': 'EstadoCamas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Ipress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IdIpress')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código Ipress')),
                ('descripcion', models.CharField(max_length=255, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ipress',
                'verbose_name_plural': 'Ipress',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoCama',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IdTipoCama')),
                ('descripcion', models.CharField(max_length=255, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'TipoCama',
                'verbose_name_plural': 'TipoCamas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IdUps')),
                ('descripcion', models.CharField(max_length=255, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ups',
                'verbose_name_plural': 'Ups',
                'ordering': ['descripcion'],
            },
        ),
    ]
