# Generated by Django 5.0.14 on 2025-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IdServicios')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AlterModelOptions(
            name='ups',
            options={'ordering': ['nombre'], 'verbose_name': 'Ups', 'verbose_name_plural': 'Ups'},
        ),
        migrations.RemoveField(
            model_name='ups',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='ups',
            name='nombre',
            field=models.CharField(default=2, max_length=100, unique=True, verbose_name='Nombre UPS'),
            preserve_default=False,
        ),
    ]
