# Generated by Django 5.0.14 on 2025-05-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_servicios_alter_ups_options_remove_ups_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cama',
            old_name='estadocama',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='cama',
            old_name='Ups',
            new_name='ups',
        ),
        migrations.AddField(
            model_name='cama',
            name='servicio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='api.servicios', verbose_name='Servicio'),
            preserve_default=False,
        ),
    ]
