# Generated by Django 5.0.14 on 2025-05-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_estadocama_cama_estado_rename_ups_cama_ups_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
