# Generated by Django 5.0.14 on 2025-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_servicios_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='codcama',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código de Cama'),
        ),
    ]
