# Generated by Django 5.0.14 on 2025-05-28 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cama_codcama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ipress',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ipress_registradas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cama',
            name='codcama',
            field=models.CharField(max_length=255, verbose_name='Código de Cama'),
        ),
        migrations.AlterUniqueTogether(
            name='cama',
            unique_together={('codcama', 'ipress')},
        ),
    ]
