# Generated by Django 5.0.14 on 2025-06-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ipress_usuario_alter_cama_codcama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='prefijo',
            field=models.CharField(default=2, max_length=10, verbose_name='Prefijo para código'),
            preserve_default=False,
        ),
    ]
