# Generated by Django 5.0.14 on 2025-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_servicio_prefijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='prefijo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Prefijo para código'),
        ),
    ]
