# Generated by Django 5.0.14 on 2025-06-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupacionCama',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IdOcupacion')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_ingreso', models.TextField()),
                ('motivo_salida', models.TextField(blank=True, null=True)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones', to='api.cama')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones_camas', to='api.paciente')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocupación de Cama',
                'verbose_name_plural': 'Ocupaciones de Camas',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
