# Generated by Django 5.0.14 on 2025-06-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ocupacioncama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaCama',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IdTransferencia')),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('cama_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='api.cama')),
                ('ocupacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='api.ocupacioncama')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de Cama',
                'verbose_name_plural': 'Transferencias de Camas',
                'ordering': ['-fecha_transferencia'],
            },
        ),
    ]
