# Generated by Django 5.0.14 on 2025-06-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transferenciacama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciacama',
            name='ocupacion_origen',
        ),
        migrations.RemoveField(
            model_name='transferenciacama',
            name='cama_destino',
        ),
        migrations.RemoveField(
            model_name='transferenciacama',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IdIngreso')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_alta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Alta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico Principal')),
                ('medico_tratante', models.CharField(max_length=255, verbose_name='Médico Tratante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='api.cama')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='api.paciente')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.DeleteModel(
            name='OcupacionCama',
        ),
        migrations.DeleteModel(
            name='TransferenciaCama',
        ),
    ]
